# Generated by Django 5.0.7 on 2024-07-27 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilizatori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('departament', models.CharField(choices=[('Gradinarit', 'Gradinarit'), ('Vopsele', 'Vopsele'), ('Tinichigerie', 'Tinichigerie'), ('Unelte', 'Unelte')], max_length=20)),
                ('city', models.CharField(default='Unknown City', max_length=100)),
                ('salariu', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='utilizator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
