# Generated by Django 5.0.7 on 2024-07-27 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilizatori',
            name='city',
        ),
        migrations.AddField(
            model_name='utilizatori',
            name='nivel',
            field=models.CharField(default='necompletat', max_length=100),
        ),
    ]
